services:
  - type: web
    name: marketplace
    runtime: node
    plan: free
    buildCommand: npm install --no-optional
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 18.17.0